language: ruby

rvm:
  - 2.3.1

cache: bundler

branches:
  only:
    - master

env:
  - RAILS_ENV=test RAKE_ENV=test

before_script:
  - npm install jade
  - npm install pug-cli

script:
  - bundle exec rake test
